Removed dev-environment folder venv/, updated .gitignore, added the b…
BuildForSDG/Farmzone pull request #7
Opened 2020-05-09 18:11 UTC by dabusharsystems

**Jimmys Changes**
I have removed the venv folder from the git repo. Each one of us has a different dev-environment setup for our development.
Instead I have added a requirement folder and  text file inside listing down the minimum               requirements or python packages needed for development. The venv folder is the reason we have many errors in codeacy.
2.  I have added a backend main folder, and inside it I added a common package. Am still updating this branch and plans to add the test envoronment for the project.

2020-05-10 05:16 UTC, Stephen-Kamau submitted a review, later dismissed

2020-05-10 23:07 UTC, dengsang requested changes
The updates are in order, 
ON your models file, probably you need to make some changes to match the fields that we earlier created  on USERS table. I have  noted some are different, this is for uniformity purposes .

2020-05-14 21:29 UTC, Stephen-Kamau approved these changes

2020-05-15 10:46 UTC, dengsang commented
I have done the approval for both the Users and forum PRs

On Fri, May 15, 2020 at 12:30 AM Stephen-Kamau <notifications@github.com>
wrote:

> *@Stephen-Kamau* approved this pull request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BuildForSDG/Farmzone/pull/7#pullrequestreview-412199205>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEF4DTQAS7D753ZX4XAG7V3RRRPF7ANCNFSM4M44X44A>
> .
>

2020-07-30 20:47 UTC, closed without merging